### ISSUE TITLE
Add Stream Content Type test

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-acceptance-tests#207] opened 2018-11-14 21:35 UTC
Need to add an AT that verifies that content types as specified by dataflow for a stream are working as expected.    Something roughly like what is in our documentation.  `stream create tuple --definition "http | filter --inputType=application/x-spring-tuple | log" --deploy`

**Comment by markpollack** [comment] 2019-03-13 19:44
I hope that `x-spring-tuple` is not in our docs!

**Comment by markpollack** [comment] 2019-03-13 19:46
looks like there is, it should be changed to json.... maybe we should have an example that uses avro.

**Comment by markpollack** [comment] 2019-03-13 20:07
Duplicate of #81?

**Comment by sabbyanandan** [comment] 2020-02-06 15:59
Not relevant anymore.

**Closed by sabbyanandan** 2020-02-06 15:59 UTC
Labels: test-coverage
